Inital Commit _signup
takuho24n/Elearning-Takuho pull request #1
Opened 2020-10-09 08:36 UTC by takuho24n

This is "signup" branch for Sign up function. 
This is my first commitment of "signup"

2020-10-12 06:16 UTC, shaniajubelag requested changes
There is this problem with the user show page. Please fix this first then push in this same branch.
![image](https://user-images.githubusercontent.com/35232348/95711520-81aa1580-0c95-11eb-8bc6-3714797b3f3d.png)

2020-10-12 07:28 UTC, takuho24n commented
> There is this problem with the user show page. Please fix this first then push in this same branch.
> ![image](https://user-images.githubusercontent.com/35232348/95711520-81aa1580-0c95-11eb-8bc6-3714797b3f3d.png)

Thank you for helping me! I've done with it!

2020-10-12 07:33 UTC, shaniajubelag commented on app/controllers/users_controller.rb
> +  def new
Change to Spaces: 2

2020-10-12 07:34 UTC, shaniajubelag commented on app/helpers/users_helper.rb
> +    end
Fix spaces here

2020-10-12 07:34 UTC, shaniajubelag commented on app/models/user.rb
> +
Change to Spaces: 2

2020-10-13 06:14 UTC, shaniajubelag commented on app/views/users/new.html.erb
> +<% provide(:title, 'Sign Up') %>
Change all lines of code from Spaces: 2 to Spaces: 4

2020-10-13 06:14 UTC, shaniajubelag requested changes
One last comment

2020-10-13 07:30 UTC, shaniajubelag approved these changes
I approve this PR

2020-10-13 07:30 UTC, merged